name: ttp_chat
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^3.0.0
  equatable: ^2.0.3
  meta: ^1.7.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  overlay_support: ^1.2.1
  image_picker: ^0.8.4+2
  logger: ^1.1.0
  shared_preferences: ^2.0.8
  retrofit: ^2.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  sticky_grouped_list: ^2.0.0-nullsafety.2
  get_it: ^7.2.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  record: ^3.0.0
  firebase_storage: ^10.0.6
  open_file: ^3.2.1
  permission_handler: ^8.2.5
  flutter_sound: ^8.4.1+1
  file_picker: ^4.1.6
  flutter_svg: ^1.0.0
  loading_animations: ^2.2.0
  # flutter_firebase_chat_core: 
  #   git:
  #     url: https://github.com/ebb-flow-group/flutter_firebase_chat_core
  #     ref: voice_message
  flutter_chat_ui:
    git:
      url: https://github.com/ebb-flow-group/flutter_chat_ui
      ref: voice_message
  audioplayers: ^0.20.1
  mime: ^1.0.1
  go_router: ^2.5.7
  route_parser: ^0.0.2
  rive: ^0.7.28


  #Unused Packages
  #url_launcher: ^6.0.12
  #cupertino_back_gesture: ^0.1.0
  #dotted_border: ^2.0.0+1
  #faker: ^1.3.0
  #http: ^0.13.4
  #pusher_client: ^2.0.0
  #pin_input_text_field: ^4.1.1
  #webview_flutter: ^2.1.1
  #readmore: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^2.0.1+2
  build_runner: any

flutter:
  assets:
    - assets/anim/
    - assets/icons/
    - assets/icons/search.svg
    - assets/images/
    - assets/welcome/
  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 800
  