name: ttp_chat
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^3.0.0
  equatable: ^2.0.3
  meta: ^1.7.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  overlay_support: ^2.0.0
  image_picker: ^0.8.5+3
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  intl: ^0.17.0
  sticky_grouped_list: ^2.1.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  record: ^4.1.1
  firebase_storage: ^10.2.16
  open_file: ^3.2.1
  permission_handler: ^9.2.0
  #flutter_sound: ^8.4.2
  file_picker: ^4.5.1
  flutter_svg: ^1.0.3
  #either we can use audioplayers or flutter sound
  audioplayers: ^0.20.1
  mime: ^1.0.2
  go_router: ^3.1.0
  route_parser: ^0.0.2
  rive: ^0.8.4
  url_launcher: ^6.1.2
  flutter_linkify: ^5.0.2
  linkify: ^4.1.0
  html: ^0.15.0
  http: ^0.13.4
  get_it: ^7.2.0
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.4.0
  flutter_screenutil: ^5.5.3+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2

flutter:
  assets:
    - assets/anim/
    - assets/icons/
    - assets/icons/search.svg
    - assets/images/
    - assets/welcome/
    - packages/ttp_chat/assets/icon-attachment.png
    - packages/ttp_chat/assets/icon-delivered.png
    - packages/ttp_chat/assets/icon-document.png
    - packages/ttp_chat/assets/icon-error.png
    - packages/ttp_chat/assets/icon-seen.png
    - packages/ttp_chat/assets/icon-send.png
    - packages/ttp_chat/assets/2.0x/icon-attachment.png
    - packages/ttp_chat/assets/2.0x/icon-delivered.png
    - packages/ttp_chat/assets/2.0x/icon-document.png
    - packages/ttp_chat/assets/2.0x/icon-error.png
    - packages/ttp_chat/assets/2.0x/icon-seen.png
    - packages/ttp_chat/assets/2.0x/icon-send.png
    - packages/ttp_chat/assets/3.0x/icon-attachment.png
    - packages/ttp_chat/assets/3.0x/icon-delivered.png
    - packages/ttp_chat/assets/3.0x/icon-document.png
    - packages/ttp_chat/assets/3.0x/icon-error.png
    - packages/ttp_chat/assets/3.0x/icon-seen.png
    - packages/ttp_chat/assets/3.0x/icon-send.png
    - packages/ttp_chat/assets/icon/add.svg
    - packages/ttp_chat/assets/icon/mic.svg
    - packages/ttp_chat/assets/icon/send.svg
    - packages/ttp_chat/assets/icon/delete.svg
    - packages/ttp_chat/assets/icon/payment.svg
    - packages/ttp_chat/assets/icon/orders.svg
    - packages/ttp_chat/assets/icon/order_details.svg
    - packages/ttp_chat/assets/icon/chat.svg
    - packages/ttp_chat/assets/anim/loading_anim.riv


  


  