name: ttp_chat
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^3.0.0
  equatable: ^2.0.3
  meta: ^1.7.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  overlay_support: ^1.2.1
  image_picker: ^0.8.4+2
  logger: ^1.1.0
  shared_preferences: ^2.0.8
  retrofit: ^2.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  sticky_grouped_list: ^2.0.0-nullsafety.2
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  record: ^3.0.0
  firebase_storage: ^10.0.6
  open_file: ^3.2.1
  permission_handler: ^8.2.5
  #flutter_sound: ^8.4.2
  file_picker: ^4.1.6
  flutter_svg: ^1.0.0
  #either we can use audioplayers or flutter sound
  audioplayers: ^0.20.1
  mime: ^1.0.1
  go_router: ^2.5.7
  route_parser: ^0.0.2
  rive: ^0.7.28
  url_launcher: ^6.0.12
  flutter_linkify: ^5.0.2
  linkify: ^4.1.0
  html: ^0.15.0
  http: ^0.13.1
  get_it: ^7.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^2.0.1+2
  build_runner: any
  dart_code_metrics: ^4.8.1

flutter:
  assets:
    - assets/anim/
    - assets/icons/
    - assets/icons/search.svg
    - assets/images/
    - assets/welcome/
    - packages/ttp_chat/assets/icon/
    - packages/ttp_chat/assets/icon-attachment.png
    - packages/ttp_chat/assets/icon-delivered.png
    - packages/ttp_chat/assets/icon-document.png
    - packages/ttp_chat/assets/icon-error.png
    - packages/ttp_chat/assets/icon-seen.png
    - packages/ttp_chat/assets/icon-send.png
    - packages/ttp_chat/assets/2.0x/icon-attachment.png
    - packages/ttp_chat/assets/2.0x/icon-delivered.png
    - packages/ttp_chat/assets/2.0x/icon-document.png
    - packages/ttp_chat/assets/2.0x/icon-error.png
    - packages/ttp_chat/assets/2.0x/icon-seen.png
    - packages/ttp_chat/assets/2.0x/icon-send.png
    - packages/ttp_chat/assets/3.0x/icon-attachment.png
    - packages/ttp_chat/assets/3.0x/icon-delivered.png
    - packages/ttp_chat/assets/3.0x/icon-document.png
    - packages/ttp_chat/assets/3.0x/icon-error.png
    - packages/ttp_chat/assets/3.0x/icon-seen.png
    - packages/ttp_chat/assets/3.0x/icon-send.png
    - packages/ttp_chat/assets/icon/add.svg
    - packages/ttp_chat/assets/icon/mic.svg
    - packages/ttp_chat/assets/icon/send.svg
    - packages/ttp_chat/assets/icon/delete.svg
    - packages/ttp_chat/assets/icon/payment.svg
    - packages/ttp_chat/assets/icon/orders.svg
    - packages/ttp_chat/assets/icon/order_details.svg
    - packages/ttp_chat/assets/anim/loading_anim.riv

  fonts:
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 500
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 800


  