// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'brand.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Brand _$BrandFromJson(Map<String, dynamic> json) => Brand(
      id: json['id'] as int,
      type: $enumDecode(_$BrandTypeEnumMap, json['type']),
      name: json['name'] as String? ?? '',
      slug: json['slug'] as String? ?? '',
      description: json['description'] as String? ?? '',
      abbreviation: json['abbreviation'] as String? ?? '',
      about: json['about'] as String? ?? '',
      delivery: json['delivery'] as bool,
      dineIn: json['dine_in'] as bool,
      takeAway: json['take_away'] as bool,
      isActive: json['is_active'] as bool,
      minDeliveryTime: json['min_delivery_time'] as int,
      maxDeliveryTime: json['max_delivery_time'] as int,
      username: json['username'] as String? ?? '',
      availability: json['availability'] as String? ?? '',
      pickupWindow: json['pickup_window'] as int?,
      phoneNumber: json['phone_number'] as String?,
      secondaryColour: json['secondary_colour'] as String?,
      backgroundColour: json['background_colour'] as String?,
      foregroundColour: json['foreground_colour'] as String?,
      logo: json['logo'] as String?,
      thumbnail: json['thumbnail'] as String?,
      menuItemPlaceholder: json['menu_item_placeholder'] as String?,
      media: json['media'] as String?,
      openingHours: json['opening_hours'] as String?,
      url: json['url'] as String?,
      contactEmail: json['contact_email'] as String?,
      whatsappAccount: json['whatsapp_account'] as String?,
      instagramAccount: json['instagram_account'] as String?,
      facebookAccount: json['facebook_account'] as String?,
      linkedinAccount: json['linkedin_account'] as String?,
      youtubeAccount: json['youtube_account'] as String?,
      twitterAccount: json['twitter_account'] as String?,
      facebookName: json['facebook_name'] as String?,
      twitterName: json['twitter_name'] as String?,
      linkedinName: json['linkedin_name'] as String?,
      youtubeName: json['youtube_name'] as String?,
      instagramName: json['instagram_name'] as String?,
      tags: (json['tags'] as List<dynamic>).map((e) => e as String).toList(),
      allowDateSelection: json['allow_date_selection'] as bool,
      uen: json['uen'] as String? ?? '',
      entityName: json['entity_name'] as String? ?? '',
      currency: json['currency'] as String? ?? '',
      holderName: json['holder_name'] as String? ?? '',
      bankName: json['bank_name'] as String? ?? '',
      accountNumber: json['account_number'] as String? ?? '',
      termAndCondition: json['term_and_condition'] as String? ?? '',
      frequencyPayout: json['frequency_payout'] as String? ?? '',
      isRegisteredEntity: json['is_registered_entity'] as bool,
      userIds:
          (json['users'] as List<dynamic>?)?.map((e) => e as int).toList() ??
              [],
    );

Map<String, dynamic> _$BrandToJson(Brand instance) => <String, dynamic>{
      'id': instance.id,
      'type': _$BrandTypeEnumMap[instance.type],
      'name': instance.name,
      'slug': instance.slug,
      'description': instance.description,
      'abbreviation': instance.abbreviation,
      'about': instance.about,
      'username': instance.username,
      'availability': instance.availability,
      'delivery': instance.delivery,
      'dine_in': instance.dineIn,
      'take_away': instance.takeAway,
      'is_active': instance.isActive,
      'min_delivery_time': instance.minDeliveryTime,
      'max_delivery_time': instance.maxDeliveryTime,
      'pickup_window': instance.pickupWindow,
      'phone_number': instance.phoneNumber,
      'secondary_colour': instance.secondaryColour,
      'background_colour': instance.backgroundColour,
      'foreground_colour': instance.foregroundColour,
      'logo': instance.logo,
      'thumbnail': instance.thumbnail,
      'menu_item_placeholder': instance.menuItemPlaceholder,
      'media': instance.media,
      'opening_hours': instance.openingHours,
      'url': instance.url,
      'contact_email': instance.contactEmail,
      'whatsapp_account': instance.whatsappAccount,
      'instagram_account': instance.instagramAccount,
      'facebook_account': instance.facebookAccount,
      'linkedin_account': instance.linkedinAccount,
      'youtube_account': instance.youtubeAccount,
      'twitter_account': instance.twitterAccount,
      'facebook_name': instance.facebookName,
      'twitter_name': instance.twitterName,
      'linkedin_name': instance.linkedinName,
      'youtube_name': instance.youtubeName,
      'instagram_name': instance.instagramName,
      'tags': instance.tags,
      'allow_date_selection': instance.allowDateSelection,
      'uen': instance.uen,
      'entity_name': instance.entityName,
      'currency': instance.currency,
      'holder_name': instance.holderName,
      'bank_name': instance.bankName,
      'account_number': instance.accountNumber,
      'term_and_condition': instance.termAndCondition,
      'frequency_payout': instance.frequencyPayout,
      'is_registered_entity': instance.isRegisteredEntity,
      'users': instance.userIds,
    };

const _$BrandTypeEnumMap = {
  BrandType.home: 'home',
  BrandType.normal: 'normal',
};
